### ISSUE TITLE
[Bug] The app crashes when trying to load Delny

### ISSUE THREAD

**Issue by YurraSickpark** [WoWs-Builder-Team/WoWs-ShipBuilder#52]
App log for the crash:

2021-11-25 15:00:59.3625|Fatal|ShipBuilder|Encountered a critical error that will end the application.
System.Collections.Generic.KeyNotFoundException: The given key 'PRPA193_130MM_HE_OF_42_YEREVAN' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WoWsShipBuilder.Core.DataProvider.AppDataHelper.GetProjectile(String projectileName)
   at WoWsShipBuilder.Core.DataUI.ShellUI.FromShellName(List`1 shellNames, List`1 modifiers, Decimal dpmFactor)
   at WoWsShipBuilder.Core.DataUI.MainBatteryUI.FromShip(Ship ship, List`1 shipConfiguration, List`1 modifiers)
   at WoWsShipBuilder.Core.DataUI.ShipUI.FromShip(Ship ship, List`1 shipConfiguration, List`1 modifiers)
   at WoWsShipBuilder.UI.ViewModels.ShipStatsControlViewModel..ctor(Ship ship, List`1 selectedConfiguration, List`1 modifiers)
   at WoWsShipBuilder.UI.ViewModels.MainWindowViewModel.InitializeData(Ship ship, String previousIndex, List`1 nextShipsIndexes, Build build)
   at WoWsShipBuilder.UI.ViewModels.MainWindowViewModel.LoadNewShip(ShipSummary summary)
   at WoWsShipBuilder.UI.ViewModels.MainWindowViewModel.NewShipSelection()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0()
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority)
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32Platform.RunLoop(CancellationToken cancellationToken)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args)
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode)
   at WoWsShipBuilder.UI.Program.Main(String[] args)

**Comment by floribe2000** [comment]
I cannot reproduce this issue neither with the current dev build nor with the latest release version (1.2.1).
I assume it may be caused by an older issue with the app's automatic updates. Can you try deleting the json directory in the appdata directory of the application so it redownloads the data?

**Comment by YurraSickpark** [comment]
It worked, issue fixed
